### ISSUE TITLE
atverskapi.delfi.lv

### ISSUE THREAD

**Issue by DandelionSprout** [Latvian-List/adblock-latvian#1]
Adblock warning after a few seconds on `https://atverskapi.delfi.lv/lv`. I propose `@@||atverskapi.delfi.lv^$generichide`

![image](https://user-images.githubusercontent.com/22780683/179372419-2d1f6261-c4dd-480b-beb5-aeeeba3c2290.png)

* Adblocker: uBlock Origin 1.43.0 + I Don't Care About Cookies 3.4.1
* Browser: Chrome 103.0.5060.114 x64
* OS: Windows 11 21H1 x64
<details>
<summary>Lists in use:</summary>

![image](https://user-images.githubusercontent.com/22780683/179372464-82053f6a-11b0-480a-bb6f-49c80df0ec19.png)

</details>

**Comment by anonymous74100** [comment]
It worked for me with:
```
atverskapi.delfi.lv#@#.adocean
atverskapi.delfi.lv#@#.ad-placement
```
