### ISSUE TITLE
Banner Ads

### ISSUE THREAD

**Issue by CbumDino** [Latvian-List/adblock-latvian#12]
Header Banner ads at: 
https://kurzemnieks.lv/
https://www.krusttevs.com/

Proposed filters: 
`kurzemnieks.lv##.banner-container.header`
`krusttevs.com###reklamas_rt`

**Comment by eporubin** [comment]
@anonymous74100  can you please also check this ones. :)

**Comment by anonymous74100** [comment]
> `kurzemnieks.lv##.banner-container.header`

From what I see, the element it hides is empty.

> `krusttevs.com###reklamas_rt`

I don't see any difference. :shrug:

**Comment by anonymous74100** [comment]
Since I don't see any harm, I'll add them anyway.

**Comment by anonymous74100** [comment]
Fixed in be98f00f84e3e70dbe16b45ad5995bb579d07ab4.
