### ISSUE TITLE
gismeteo.lv

### ISSUE THREAD

**Issue by DandelionSprout** [Latvian-List/adblock-latvian#3]
2 large placeholders on `https://www.gismeteo.lv/`. I propose `gismeteo.lv##.placeholder`

![image](https://user-images.githubusercontent.com/22780683/179373452-81bc91a8-bb11-430e-9a16-92615a6652fb.png)

* Adblocker: uBlock Origin 1.43.0 + I Don't Care About Cookies 3.4.1
* Browser: Chrome 103.0.5060.114 x64
* OS: Windows 11 21H1 x64
<details>
<summary>Lists in use:</summary>

![image](https://user-images.githubusercontent.com/22780683/179372464-82053f6a-11b0-480a-bb6f-49c80df0ec19.png)

</details>

**Comment by anonymous74100** [comment]
It feels a little too generic, but ok.
