### ISSUE TITLE
cvmarket.lv

### ISSUE THREAD

**Issue by DandelionSprout** [Latvian-List/adblock-latvian#6]
Placeholder near the top on `https://www.cvmarket.lv/`. I propose `cvmarket.lv##.with_banner`

![image](https://user-images.githubusercontent.com/22780683/179374094-8680d166-e961-4a4e-9fd1-507b190d1d68.png)

* Adblocker: uBlock Origin 1.43.0 + I Don't Care About Cookies 3.4.1
* Browser: Chrome 103.0.5060.114 x64
* OS: Windows 11 21H1 x64
<details>
<summary>Lists in use:</summary>

![image](https://user-images.githubusercontent.com/22780683/179372464-82053f6a-11b0-480a-bb6f-49c80df0ec19.png)

</details>

**Comment by anonymous74100** [comment]
Thanks, added!
