### ISSUE TITLE
`Redirect` directive in github hosted file

### ISSUE THREAD

**Issue by Alex-302** [Latvian-List/adblock-latvian#7]
Hi
Is `! Redirect: https://raw.githubusercontent.com/Latvian-List/adblock-latvian/master/lists/latvian-list.txt` required in `https://raw.githubusercontent.com/Latvian-List/adblock-latvian/master/lists/latvian-list.txt` ?

**Comment by anonymous74100** [comment]
You're asking if it won't create a loop, right? Good question... I'll remove it.
